# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/Projects_C/Compiler copy"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/Projects_C/Compiler copy"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/Projects_C/Compiler copy/CMakeFiles" "/home/Projects_C/Compiler copy//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/Projects_C/Compiler copy/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named javalib

# Build rule for target.
javalib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 javalib
.PHONY : javalib

# fast build rule for target.
javalib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/build
.PHONY : javalib/fast

#=============================================================================
# Target rules for targets named Java_Compiler

# Build rule for target.
Java_Compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Java_Compiler
.PHONY : Java_Compiler

# fast build rule for target.
Java_Compiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Java_Compiler.dir/build.make CMakeFiles/Java_Compiler.dir/build
.PHONY : Java_Compiler/fast

src/Analyzer.o: src/Analyzer.cpp.o
.PHONY : src/Analyzer.o

# target to build an object file
src/Analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Analyzer.cpp.o
.PHONY : src/Analyzer.cpp.o

src/Analyzer.i: src/Analyzer.cpp.i
.PHONY : src/Analyzer.i

# target to preprocess a source file
src/Analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Analyzer.cpp.i
.PHONY : src/Analyzer.cpp.i

src/Analyzer.s: src/Analyzer.cpp.s
.PHONY : src/Analyzer.s

# target to generate assembly for a file
src/Analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Analyzer.cpp.s
.PHONY : src/Analyzer.cpp.s

src/CodeGen.o: src/CodeGen.cpp.o
.PHONY : src/CodeGen.o

# target to build an object file
src/CodeGen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/CodeGen.cpp.o
.PHONY : src/CodeGen.cpp.o

src/CodeGen.i: src/CodeGen.cpp.i
.PHONY : src/CodeGen.i

# target to preprocess a source file
src/CodeGen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/CodeGen.cpp.i
.PHONY : src/CodeGen.cpp.i

src/CodeGen.s: src/CodeGen.cpp.s
.PHONY : src/CodeGen.s

# target to generate assembly for a file
src/CodeGen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/CodeGen.cpp.s
.PHONY : src/CodeGen.cpp.s

src/Error.o: src/Error.cpp.o
.PHONY : src/Error.o

# target to build an object file
src/Error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Error.cpp.o
.PHONY : src/Error.cpp.o

src/Error.i: src/Error.cpp.i
.PHONY : src/Error.i

# target to preprocess a source file
src/Error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Error.cpp.i
.PHONY : src/Error.cpp.i

src/Error.s: src/Error.cpp.s
.PHONY : src/Error.s

# target to generate assembly for a file
src/Error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Error.cpp.s
.PHONY : src/Error.cpp.s

src/Parser.o: src/Parser.cpp.o
.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i
.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s
.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/Parser_copy.o: src/Parser_copy.cpp.o
.PHONY : src/Parser_copy.o

# target to build an object file
src/Parser_copy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Parser_copy.cpp.o
.PHONY : src/Parser_copy.cpp.o

src/Parser_copy.i: src/Parser_copy.cpp.i
.PHONY : src/Parser_copy.i

# target to preprocess a source file
src/Parser_copy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Parser_copy.cpp.i
.PHONY : src/Parser_copy.cpp.i

src/Parser_copy.s: src/Parser_copy.cpp.s
.PHONY : src/Parser_copy.s

# target to generate assembly for a file
src/Parser_copy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Parser_copy.cpp.s
.PHONY : src/Parser_copy.cpp.s

src/Scanner.o: src/Scanner.cpp.o
.PHONY : src/Scanner.o

# target to build an object file
src/Scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Scanner.cpp.o
.PHONY : src/Scanner.cpp.o

src/Scanner.i: src/Scanner.cpp.i
.PHONY : src/Scanner.i

# target to preprocess a source file
src/Scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Scanner.cpp.i
.PHONY : src/Scanner.cpp.i

src/Scanner.s: src/Scanner.cpp.s
.PHONY : src/Scanner.s

# target to generate assembly for a file
src/Scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Scanner.cpp.s
.PHONY : src/Scanner.cpp.s

src/Scanner_copy.o: src/Scanner_copy.cpp.o
.PHONY : src/Scanner_copy.o

# target to build an object file
src/Scanner_copy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Scanner_copy.cpp.o
.PHONY : src/Scanner_copy.cpp.o

src/Scanner_copy.i: src/Scanner_copy.cpp.i
.PHONY : src/Scanner_copy.i

# target to preprocess a source file
src/Scanner_copy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Scanner_copy.cpp.i
.PHONY : src/Scanner_copy.cpp.i

src/Scanner_copy.s: src/Scanner_copy.cpp.s
.PHONY : src/Scanner_copy.s

# target to generate assembly for a file
src/Scanner_copy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/Scanner_copy.cpp.s
.PHONY : src/Scanner_copy.cpp.s

src/SymbolTable.o: src/SymbolTable.cpp.o
.PHONY : src/SymbolTable.o

# target to build an object file
src/SymbolTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/SymbolTable.cpp.o
.PHONY : src/SymbolTable.cpp.o

src/SymbolTable.i: src/SymbolTable.cpp.i
.PHONY : src/SymbolTable.i

# target to preprocess a source file
src/SymbolTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/SymbolTable.cpp.i
.PHONY : src/SymbolTable.cpp.i

src/SymbolTable.s: src/SymbolTable.cpp.s
.PHONY : src/SymbolTable.s

# target to generate assembly for a file
src/SymbolTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/SymbolTable.cpp.s
.PHONY : src/SymbolTable.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Java_Compiler.dir/build.make CMakeFiles/Java_Compiler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Java_Compiler.dir/build.make CMakeFiles/Java_Compiler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/javalib.dir/build.make CMakeFiles/javalib.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Java_Compiler.dir/build.make CMakeFiles/Java_Compiler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Java_Compiler"
	@echo "... javalib"
	@echo "... src/Analyzer.o"
	@echo "... src/Analyzer.i"
	@echo "... src/Analyzer.s"
	@echo "... src/CodeGen.o"
	@echo "... src/CodeGen.i"
	@echo "... src/CodeGen.s"
	@echo "... src/Error.o"
	@echo "... src/Error.i"
	@echo "... src/Error.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Parser_copy.o"
	@echo "... src/Parser_copy.i"
	@echo "... src/Parser_copy.s"
	@echo "... src/Scanner.o"
	@echo "... src/Scanner.i"
	@echo "... src/Scanner.s"
	@echo "... src/Scanner_copy.o"
	@echo "... src/Scanner_copy.i"
	@echo "... src/Scanner_copy.s"
	@echo "... src/SymbolTable.o"
	@echo "... src/SymbolTable.i"
	@echo "... src/SymbolTable.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

